// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"speech.local/apps/api-server/internal/handler"
	"speech.local/apps/api-server/internal/repository"
	"speech.local/apps/api-server/internal/usecase"
	"speech.local/packages/config"
	"speech.local/packages/db"
	"speech.local/packages/storage"
)

// Injectors from wire.go:

// InitializeTaskDependencies injects all dependencies for task handler
func InitializeTaskDependencies() (*handler.TaskHandler, error) {
	appConfig, err := NewAppConfig()
	if err != nil {
		return nil, err
	}
	s3Storage, err := NewS3Storage(appConfig)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(appConfig)
	if err != nil {
		return nil, err
	}
	taskRepo := repository.NewTaskRepo(db)
	taskUseCase := NewTaskUseCase(s3Storage, taskRepo)
	taskHandler := NewTaskHandler(taskUseCase)
	return taskHandler, nil
}

// wire.go:

var ProviderSet = wire.NewSet(

	NewAppConfig,
	ProvideDB,

	NewS3Storage, wire.Bind(new(repository.StorageRepo), new(*storage.S3Storage)), repository.NewTaskRepo, NewTaskUseCase,
	NewTaskHandler,
)

func NewAppConfig() (*config.AppConfig, error) {
	return config.NewAppConfig()
}

// ProvideDB 負責從 Config 提取 DBConfig 並建立 *gorm.DB 連線
func ProvideDB(cfg *config.AppConfig) (*gorm.DB, error) {
	return db.NewPostgresConn(cfg.DBConfig)
}

// NewS3Storage 負責從 Config 提取 S3Config 並建立 S3 Client
func NewS3Storage(cfg *config.AppConfig) (*storage.S3Storage, error) {
	return storage.NewS3Storage(cfg.S3Config)
}

func NewTaskUseCase(storageRepo repository.StorageRepo, taskRepo repository.TaskRepo) usecase.TaskUseCase {
	return usecase.NewTaskUseCase(storageRepo, taskRepo)
}

func NewTaskHandler(taskUsecase usecase.TaskUseCase) *handler.TaskHandler {
	return handler.NewTaskHandler(taskUsecase)
}
