// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/google/wire"
	"github.com/uptrace/opentelemetry-go-extra/otelgorm"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"speech.local/apps/api-server/internal/handler"
	"speech.local/apps/api-server/internal/repository"
	"speech.local/apps/api-server/internal/usecase"
	"speech.local/packages/config"
	"speech.local/packages/db"
	"speech.local/packages/redis"
	"speech.local/packages/storage"
	"speech.local/packages/telemetry"
)

// Injectors from wire.go:

// InitializeTaskDependencies injects all dependencies for task handler
func InitializeTaskDependencies() (*handler.TaskHandler, error) {
	appConfig, err := NewAppConfig()
	if err != nil {
		return nil, err
	}
	s3Storage, err := NewS3Storage(appConfig)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDB(appConfig)
	if err != nil {
		return nil, err
	}
	taskRepo := repository.NewTaskRepo(db)
	redisClient, err := ProvideRedisClient(appConfig)
	if err != nil {
		return nil, err
	}
	pubSubRepo := repository.NewPubSubRepo(redisClient)
	taskUseCase := NewTaskUseCase(s3Storage, taskRepo, pubSubRepo, appConfig)
	logger, err := NewLogger(appConfig)
	if err != nil {
		return nil, err
	}
	taskHandler := NewTaskHandler(taskUseCase, logger, appConfig)
	return taskHandler, nil
}

// wire.go:

var ProviderSet = wire.NewSet(

	NewAppConfig,
	ProvideDB,

	NewS3Storage, wire.Bind(new(repository.StorageRepo), new(*storage.S3Storage)), ProvideRedisClient, repository.NewPubSubRepo, repository.NewTaskRepo, NewTaskUseCase,
	NewLogger,
	NewTaskHandler,
)

// NewAppConfig 載入環境變數
func NewAppConfig() (*config.AppConfig, error) {
	return config.NewAppConfig()
}

// ProvideTelemetryConfig 提取 TelemetryConfig
func ProvideTelemetryConfig(cfg *config.AppConfig) telemetry.Config {
	return cfg.TelemetryConfig
}

// ProvideDB 負責從 Config 提取 DBConfig 並建立 *gorm.DB 連線
func ProvideDB(cfg *config.AppConfig) (*gorm.DB, error) {
	gdb, err := db.NewPostgresConn(cfg.DBConfig)
	if err != nil {
		return nil, err
	}
	if err := gdb.Use(otelgorm.NewPlugin()); err != nil {
		return nil, err
	}
	return gdb, nil
}

// NewS3Storage 負責從 Config 提取 S3Config 並建立 S3 Client
func NewS3Storage(cfg *config.AppConfig) (*storage.S3Storage, error) {
	return storage.NewS3Storage(cfg.S3Config)
}

// ProvideRedisClient 負責從 Config 提取 RedisConfig 並建立 Redis Client
func ProvideRedisClient(cfg *config.AppConfig) (*redis.RedisClient, error) {
	return redis.NewRedisClient(cfg.RedisConfig)
}

func NewTaskUseCase(storageRepo repository.StorageRepo, taskRepo repository.TaskRepo, pubSubRepo repository.PubSubRepo, cfg *config.AppConfig) usecase.TaskUseCase {
	return usecase.NewTaskUseCase(storageRepo, taskRepo, pubSubRepo, cfg.Debug)
}

func NewLogger(cfg *config.AppConfig) (*zap.Logger, error) {
	return telemetry.NewLogger(cfg.TelemetryConfig.ServiceName)
}

func NewTaskHandler(taskUsecase usecase.TaskUseCase, logger *zap.Logger, cfg *config.AppConfig) *handler.TaskHandler {
	return handler.NewTaskHandler(taskUsecase, logger, cfg.Debug)
}

// InitializeTelemetry 初始化 OpenTelemetry
func InitializeTelemetry(cfg telemetry.Config) (func(context.Context) error, error) {
	return telemetry.InitTracer(cfg)
}
