// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"speech.local/apps/outbox-relay/internal/repository"
	"speech.local/apps/outbox-relay/internal/usecase"
	"speech.local/packages/config"
	"speech.local/packages/db"
	"speech.local/packages/mq"
)

// Injectors from wire.go:

// InitializeRelayService 初始化整個 Relay 服務的依賴注入
func InitializeRelayService() (usecase.RelayService, error) {
	appConfig, err := NewAppConfig()
	if err != nil {
		return nil, err
	}
	rabbitMQPublisher, err := ProvideRabbitMQPublisher(appConfig)
	if err != nil {
		return nil, err
	}
	gormDB, err := ProvideDB(appConfig)
	if err != nil {
		return nil, err
	}
	outboxDAO := db.NewOutboxDAO(gormDB)
	relayService := NewRelayService(rabbitMQPublisher, outboxDAO)
	return relayService, nil
}

// wire.go:

var ProviderSet = wire.NewSet(

	NewAppConfig,
	ProvideDB,

	ProvideRabbitMQPublisher, wire.Bind(new(repository.Publisher), new(*mq.RabbitMQPublisher)), db.NewOutboxDAO, wire.Bind(new(repository.OutboxRepo), new(*db.OutboxDAO)), NewRelayService,
)

// NewAppConfig 載入環境變數
func NewAppConfig() (*config.AppConfig, error) {
	return config.NewAppConfig()
}

// ProvideDB 從 AppConfig 提取 DBConfig 並建立 *gorm.DB
func ProvideDB(cfg *config.AppConfig) (*gorm.DB, error) {
	return db.NewPostgresConn(cfg.DBConfig)
}

// ProvideRabbitMQPublisher 從 AppConfig 提取 MQURL 並建立 RabbitMQ 實作
func ProvideRabbitMQPublisher(cfg *config.AppConfig) (*mq.RabbitMQPublisher, error) {
	return mq.NewRabbitMQPublisher(cfg.MQURL)
}

// NewRelayService 建立業務邏輯層
func NewRelayService(publisher repository.Publisher, outboxRepo repository.OutboxRepo) usecase.RelayService {
	return usecase.NewRelayService(publisher, outboxRepo)
}
